# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
	ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'
	ENV['FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT'] = '1'
end

platform :ios do
	desc "Push a new beta build to TestFlight"
	lane :beta do
  	# increment_build_number
		#build_number = get_build_number(xcodeproj: "JioCinema.xcodeproj")
		# build_app(workspace: "JioTalks.xcworkspace", scheme: "JioTalks")
		  # increment_build(app_identifier: Zattoo::AppIdentifier::AppleStore)

		gym(
			workspace: "JioCinema.xcworkspace",
			scheme: "JioCinema",
			export_method: 'app-store',
			)
		# upload_to_testflight

	# Submit to iTunes Connect
	pilot(
		app_platform: "appletvos",
		skip_submission: true,
		skip_waiting_for_build_processing: true
		)
	clean_build_artifacts 
    #build_app(workspace: "JioCinema.xcworkspace", scheme: "JioCinema")
    #upload_to_testflight
end

private_lane :increment_build do |options|
	increment_build_number({
		build_number: latest_testflight_build_number(app_identifier: options[:app_identifier], platform: 'appletvos') + 1
	})
end
end
